Random updates
ConchuOD/nipa pull request #9
Opened 2023-01-09 15:22 UTC by ConchuOD

A bunch of random updates, entirely untested so far.
Some bits of cleanup, followed by Nathan's suggestion of how to cut down on the time do the before/after warning checks - hopefully that'll make it viable to run llvm again.

2023-01-10 12:52 UTC, ConchuOD commented
So, this needs a little bit of sequencing to massage my jenkins pipeline, with the CROSS_COMPILE bit. I think it should be okay, but maybe not.

I did a minor rename along the way to align the name of the.

I ran NIPA in my CI with this & it seemed okay - but the processing time for a patch has doubled thanks to enabling clang/LLVM.
It takes, for an arbitrary set of resources, 30 mins to build allmodconfig with clang & 11 minutes for the second build, where the only change was a comment.
The correspoding times were 20 & 12 for gcc. There's something clearly still wrong with how the rebuilding is done.
It's with ccache AND rebuilding in the same directory so you'd hope that it'd really take very little time to do the rebuild, but that's not the case.

2023-01-10 12:56 UTC, ConchuOD commented on tests_rv/patch/build_rv64_clang_allmodconfig/build_rv64_clang_allmodconfig.sh
> +	W=1 CROSS_COMPILE=riscv64-linux- config default \
Building Guo's comment patch today, this took 28 minutes.

2023-01-10 12:56 UTC, ConchuOD commented on tests_rv/patch/build_rv64_clang_allmodconfig/build_rv64_clang_allmodconfig.sh
> +	W=1 CROSS_COMPILE=riscv64-linux- config default \
This took 11 mnutes

2023-01-10 12:58 UTC, ConchuOD reviewed
Added the numbers to the relevant places for context & here's the tuxmake output...

gcc:

W: Support for running offline not available (unshare: unshare failed: Operation not permitted)
I: config: PASS in 0:00:01.839426
I: default: PASS in 0:20:47.301790
I: build output in /ci/workspace/OC_ES_linux-test_riscv-patchwork__4/nipa/trees_rv/fixes/build
W: Support for running offline not available (unshare: unshare failed: Operation not permitted)
I: config: PASS in 0:00:01.428265
I: default: PASS in 0:10:05.979234
I: build output in /ci/workspace/OC_ES_linux-test_riscv-patchwork__4/nipa/trees_rv/fixes/build

llvm:
W: Support for running offline not available (unshare: unshare failed: Operation not permitted)
I: config: PASS in 0:00:03.884311
I: default: PASS in 0:28:19.853824
I: build output in /ci/workspace/OC_ES_linux-test_riscv-patchwork__4/nipa/trees_rv/fixes/build
W: Support for running offline not available (unshare: unshare failed: Operation not permitted)
I: config: PASS in 0:00:02.063537
I: default: PASS in 0:11:47.520979
I: build output in /ci/workspace/OC_ES_linux-test_riscv-patchwork__4/nipa/trees_rv/fixes/build

2023-01-10 12:58 UTC, ConchuOD commented on tests_rv/patch/build_rv64_gcc_allmodconfig/build_rv64_gcc_allmodconfig.sh
> +	-K CONFIG_GCC_PLUGINS=n W=1 CROSS_COMPILE=riscv64-linux- config default \
This one took 20 minutes

2023-01-10 12:58 UTC, ConchuOD commented on tests_rv/patch/build_rv64_gcc_allmodconfig/build_rv64_gcc_allmodconfig.sh
> +	-K CONFIG_GCC_PLUGINS=n W=1 CROSS_COMPILE=riscv64-linux- config default \
and this took 12

2023-01-10 13:17 UTC, ConchuOD commented
> I ran NIPA in my CI with this & it seemed okay - but the processing time for a patch has doubled thanks to enabling clang/LLVM. It takes, for an arbitrary set of resources, 30 mins to build allmodconfig with clang & 11 minutes for the second build, where the only change was a comment. The correspoding times were 20 & 12 for gcc. There's something clearly still wrong with how the rebuilding is done. It's with ccache AND rebuilding in the same directory so you'd hope that it'd really take very little time to do the rebuild, but that's not the case.

As we said last time Bjorn, it's the stage that looks like "CC [M[ drivers/foo/var/baz.mod.o" that takes forever. I am not sure what the stage is called though...

2023-01-12 09:25 UTC, bjoto commented
> > I ran NIPA in my CI with this & it seemed okay - but the processing time for a patch has doubled thanks to enabling clang/LLVM. It takes, for an arbitrary set of resources, 30 mins to build allmodconfig with clang & 11 minutes for the second build, where the only change was a comment. The correspoding times were 20 & 12 for gcc. There's something clearly still wrong with how the rebuilding is done. It's with ccache AND rebuilding in the same directory so you'd hope that it'd really take very little time to do the rebuild, but that's not the case.
> 
> As we said last time Bjorn, it's the stage that looks like "CC [M[ drivers/foo/var/baz.mod.o" that takes forever. I am not sure what the stage is called though...

(First I thought it was missing the `-z none` but nope.) 

So the module build for clang is the step that takes forever? Are you getting ccache hits?

2023-01-12 09:45 UTC, bjoto requested changes

2023-01-12 09:45 UTC, bjoto commented on tests_rv/patch/build_rv64_clang_allmodconfig/build_rv64_clang_allmodconfig.sh
> +	config default \
CONFIG_RANDSTRUCT_NONE=y missing -- this messes up the ccache.

2023-01-12 09:45 UTC, bjoto commented on tests_rv/patch/build_rv64_gcc_allmodconfig/build_rv64_gcc_allmodconfig.sh
> +	config default \
Nit: remove quoted space before -K ...

2023-01-12 23:32 UTC, ConchuOD commented
@bjoto So I had a bit of a think about the "leaked" builddir stuff and I came to the conclusion that leaking it is a bad idea.
I'm not sure that we can ever "trust" that someone's patchset does not do entirely botched things with the build system by hacking at kbuild. Having implemented a way to clean the build directories only at the start of a patch series I then ripped it out & put the rm $tmpdir_b back in!

Also, I disabled the clang build again temporarily. I want to build a PGOed toolchain as Nathan promises significant time savings from doing so. I'll probably kick that off tomorrow evening before I leave the office as his script will do a bunch of kernel builds to generate the profile & I'd rather that be the toolchain that we do clang/LLVM stuff with.

2023-01-13 09:47 UTC, bjoto commented
Far enough! LGTM!

2023-01-13 09:47 UTC, bjoto approved these changes
LGTM!

2023-01-13 09:51 UTC, merged